Готова восьмая проектная работа.
pavel-kir/zakrivayuschiy-teg-final pull request #1
Opened 2024-04-06 06:21 UTC by pavel-kir

Отправляю на ревью.

2024-04-06 09:19 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа. _Пожалуйста, не торопитесь, и после исправления проверяйте исправление всех критических комментариев и соответствие макету на всех брейкпоинтах._


_ Что понравилось:_

- цвет в символах кнопок заполняется корректно 
- Правильное форматирование
- Корректная структура HTML
- работают темы
- корректные анимации
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Хорошо адаптирована вся страница

_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично»**

- https://disk.yandex.ru/i/Y5YkLPJuJUI3xQ Это декоративный шрифт, используйте значение fantasy в качестве альтернативы для каждого св-ва font-family https://doka.guide/css/font-family/ А так же нужно заменить значение альтернативного шрифта на вариант [Веб-безопасный альтернативный декоративный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/) из соответствующего раздела

- По заданию проект нужно выложить на GitHub Pages, из-за авто-тестов ссылку можно в Readme не добавлять


- **При исправлении для одной из тем (светлой/тёмной) обязательно проверяйте, чтобы при такой же автотеме (светлой/тёмной) было соответствующее исправление.** Это напоминалка, а не конкретное исправление.



- Для ширины экрана 375px _не совпадает с макетом_ :
  -  https://disk.yandex.ru/i/HIOXogOMg2B9NQ высота строки


_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- CSS-правила в коде желательно распологать в примерном соответствии с позицией элементов в DOM.

- Для всех функций ` var() ` в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. 

- Про альтернативный текст для картинок https://habr.com/ru/post/341810/

- Можно использовать удобное сокращение  [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background)
- Для единообразного форматирования документов в VSCode лучше положить файл `.editorconfig` в корневой каталог
- А так же можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`



**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-04-06 09:19 UTC, Avaakum commented on styles/style.css
> +@supports((text-stroke: 1px #000) or (-webkit-text-stroke: 1px #000)) {
---

**Отлично:**

/*+++ Поддержка text-stroke и -webkit-text-stroke проверена директивой @supports через оператор "или"*/

2024-04-06 09:19 UTC, Avaakum commented on styles/style.css
> +  0 -1px var(--stroke-color, rgb(255 255 255 / 0.5));
---

**Отлично:**

/*+++ Хорошо реализована тень*/

2024-04-06 09:19 UTC, Avaakum commented on styles/style.css
> +#modal[open] {
---

**Отлично:**

/*+++ 
Стили для попапа должны быть присвоены при добавленном атрибуте open. 
*/

2024-04-06 09:19 UTC, Avaakum commented on fonts/fonts.css
> +    url(./Inter-Variable.woff2) format('woff2-variations');
---

**Отлично:**

/*+++   при подключении вариативного шрифта должны быть указаны верные форматы: как обновленный woff2 supports variations, так и устаревающий woff2-variations;*/

2024-04-06 09:19 UTC, Avaakum commented on fonts/fonts.css
> +  font-weight: 400 785;
---

**Отлично:**

/*+++ Корректный диапазон веса шрифта*/

2024-04-06 09:19 UTC, Avaakum commented on index.html
> +    <meta name="color-scheme" content="dark light">
Цветовые схемы описаны в теге, но так как по умолчанию вы задаёте для светлой, а медиа выражение для тёмной, значит по умолчанию должно быть  светлая-тёмная в теге мета

2024-04-06 09:19 UTC, Avaakum commented on index.html
>    </head>
---

**Отлично:**

Корректно заполнен `head`

2024-04-06 09:19 UTC, Avaakum commented on styles/themes.css
> +  }
---

**Отлично:**

Мы изначально выбираем одну тему как основную(тёмную или светлую), и страница должна корректно отображаться при выборе авто-темы с той, которой мы задавали как основную. 
    -   Например, если мы решили использовать по-умолчанию тему и автотему тёмную(эту тему мы как раз указываем в html в метатеге первой), то и стили должны быть добавлены в файлах variables и style.css изначально под неё и работать и при автотеме и просто тёмной теме. При включении светлой темы применяются значения переменных, указаных для класса светлой темы. А при включении авто-темы "светлой" уже будет будет использовано медиа правило ` prefers-color-scheme: light ` из соответствующего файла, в котором дублируются стили от светлой темы, только уже не для класса, а для селектора :root, плюс остальные моменты, как показ rec в предыдущей работе и прочее

2024-04-06 09:19 UTC, Avaakum commented on styles/themes.css
> +  .page.theme-auto {
Используйте селектор `:root` , как в файле variables, только там для авто-светлой темы

2024-04-06 09:19 UTC, Avaakum commented on index.html
> +        <li class="card block__size">
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2024-04-06 09:19 UTC, Avaakum commented on index.html
> +        <dialog id="modal">
---

**Отлично:**

Корректно реализован попап, задний фон и стилизация

2024-04-06 09:19 UTC, Avaakum commented on index.html
> +          <form  class="modal-form" method="dialog">
---

**Отлично:**

корректное значение метода формы для нативного закрытия диалога

2024-04-06 09:19 UTC, Avaakum commented on index.html
> +            <button class="button modal-button">
---

**Можно лучше:**

тип кнопки должен быть submit в данном случае что бы всё работало. Нам нужен тип кнопки для отправки формы, что бы окно корректно закрывалось.

2024-04-06 13:12 UTC, pavel-kir commented on styles/themes.css
> +  .page.theme-auto {
Селектор типа `:root.theme-light`, не работает, так как скрипт добавляет тему не к html, а к body.

2024-04-07 04:40 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! Поздравляю  с завершением курса!




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-04-07 07:45 UTC, merged